move_tasks_deadline_js/urls.py
from django.urls import path
from .views.index import index
from .views.move_button import move_button
from .views.move_deadline import move_deadline
from .views.bind_button import bind_button
from .views.unbind_button import unbind_button


app_name = 'move_tasks_deadline_js'
urlpatterns = [
    path('', index, name='index'),
    path('move_button', move_button, name='move_button'),
    path('move_deadline', move_deadline, name='move_deadline'),
    path('bind_button', bind_button, name='bind_button'),
    path('unbind_button', unbind_button, name='unbind_button'),
]

urls.py
import settings
from django.contrib import admin
from django.urls import path, include
from post_currency.views import *
from django.conf.urls.static import static

from start.views.start import start

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', start),
    path('tasks/', include('tasks.urls')),
    path('ones/', include('ones_fresh_unf_with_b24.urls')),
    path('crmfields/', include('crmfields.urls')),
    path('callsuploader/', include('callsuploader.urls')),
    path('duplicatefinder/', include('duplicatefinder.urls')),
    path('urlmanager/', include('usermanager.urls')),
    path('selectuser/', include('selectuser.urls')),
    path('company_on_map/', include('company_on_map.urls')),
    path('robot/', include('robot_currency.urls', 'bitrix_robot_currency')),
    path('employeegrid/', include('employeegrid.urls')),
    path('product_list_in_excel/', include('product_list_excel.urls')),
    path('allcompbizproc/', include('allcompbizproc.urls')),
    path('import_company_google/', include('import_company_google.urls')),
    path('demo_data_in_bitrix/', include('demo_data_in_bitrix.urls')),
    path('sample_tg_bot/', include('sample_tg_bot.urls')),
    path('audio_recognition/', include('audio_recognition.urls')),
    path('best_call_manager/', include('best_call_manager.urls')),
    path('calls_to_telegram/', include('calls_to_telegram.urls')),
    path('tg_open_ai/', include('tg_openai_bot.urls')),
    path('deal_for_powerbi/', include('deal_for_powerbi.urls')),
    path('autocomplete_crm_tasks/', include('autocomplete_crm_tasks.urls')),
    path('move_tasks_deadline_js/', include('move_tasks_deadline_js.urls', 'move_tasks_deadline_js')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

move_tasks_deadline_js/models.py
from django.db import models

# Create your models here.

move_tasks_deadline_js/views/bind_button.py
from django.shortcuts import redirect
from django.urls import reverse
from django.conf import settings
from django.http import Http404
from ..utils.is_handler_bound import is_bound
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth


@main_auth(on_cookies=True)
def bind_button(request):
    """Привязываем хендлер к окну просмотра задачи"""
    if request.method != "POST":
        raise Http404()

    handler_type = request.GET.get("type")

    if request.bitrix_user.is_admin and handler_type in ["js", "admin", "self"]:
        if not is_bound(request.bitrix_user_token, handler_type):
            request.bitrix_user_token.call_api_method("placement.bind", params={
                "PLACEMENT": "TASK_VIEW_SIDEBAR",
                "HANDLER": settings.DOMAIN + reverse('move_tasks_deadline_js:move_button') + "?type=" + handler_type
            })

    return redirect(reverse("move_tasks_deadline_js:index"))

move_tasks_deadline_js/views/index.py
from django.shortcuts import render
from ..utils.is_handler_bound import is_bound
from django.views.decorators.csrf import requires_csrf_token
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth


@main_auth(on_cookies=True)
def index(request):
    """Страница из списка с приложениями, на которой можно привязать
    хендлер к окну просмотра задачи"""
    bound = {}
    for handler_type in ["js", "admin", "self"]:
        bound[handler_type] = is_bound(request.bitrix_user_token, handler_type)

    return render(request, 'move_tasks_deadline_js/index.html', {
        "bound": bound
    })

move_tasks_deadline_js/views/move_button.py
from django.shortcuts import render
from django.http import Http404
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth


@main_auth(on_start=True, set_cookie=True)
def move_button(request):
    """Страница с кнопкой сдвига крайнего срока для вставки в окно просмотра задачи"""
    button_type = request.GET.get("type")

    if button_type not in ["js", "admin", "self"]:
        raise Http404()

    script_name = button_type
    if button_type == "self":
        script_name = "admin"

    path_to_script = f"move_tasks_deadline_js/{ script_name }.js"

    return render(request, 'move_tasks_deadline_js/move_button.html', {
        "button_type": button_type,
        "path_to_script": path_to_script
    })

move_tasks_deadline_js/views/move_deadline.py
from django.shortcuts import render
from django.http import Http404
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth
from integration_utils.bitrix24.models.bitrix_user import BitrixUser
from datetime import datetime, timedelta


@main_auth(on_cookies=True)
def move_deadline(request):
    """Сдвигает крайний срок задачи на день по токену админа"""
    if request.method != "POST":
        raise Http404()

    button_type = request.GET.get("type")

    if button_type not in ["admin", "self"]:
        raise Http404()

    resp = render(request, 'move_tasks_deadline_js/move_button.html', {
        "button_type": button_type,
        "path_to_script": "move_tasks_deadline_js/admin.js"
    })

    task_id = request.POST.get("task_id")

    if not task_id:
        return resp

    but = BitrixUser.objects.get(pk=1).bitrix_user_token
    response = but.call_api_method("tasks.task.get", params={
        "taskId": task_id,
        "select": ["DEADLINE", "CREATED_BY"]
    })

    if button_type == "self":
        if int(response["result"]["task"]["createdBy"]) != request.bitrix_user.bitrix_id:
            return resp

    deadline_iso = response["result"]["task"]["deadline"]

    if not deadline_iso:
        return resp

    deadline = datetime.fromisoformat(deadline_iso)
    deadline += timedelta(days=1)
    deadline_iso = deadline.isoformat()

    but.call_api_method("tasks.task.update", params={
        "taskId": task_id,
        "fields": {"DEADLINE": deadline_iso}
    })

    return resp

move_tasks_deadline_js/views/unbind_button.py
from django.shortcuts import redirect
from django.urls import reverse
from django.conf import settings
from django.http import Http404
from ..utils.is_handler_bound import is_bound
from integration_utils.bitrix24.bitrix_user_auth.main_auth import main_auth


@main_auth(on_cookies=True)
def unbind_button(request):
    """Отвязываем хендлер от окна просмотра задачи"""
    if request.method != "POST":
        raise Http404()

    handler_type = request.GET.get("type")

    if request.bitrix_user.is_admin and handler_type in ["js", "admin", "self"]:
        if is_bound(request.bitrix_user_token, handler_type):
            request.bitrix_user_token.call_api_method("placement.unbind", params={
                "PLACEMENT": "TASK_VIEW_SIDEBAR",
                "HANDLER": settings.DOMAIN + reverse('move_tasks_deadline_js:move_button') + "?type=" + handler_type
            })

    return redirect(reverse("move_tasks_deadline_js:index"))

move_tasks_deadline_js/templates/move_tasks_deadline_js/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title></title>
    <meta charset="UTF-8">
</head>
<body>
{% if request.bitrix_user.is_admin %}
    {% for handler_type, is_bound in bound.items %}
        <h3>{{ handler_type }}</h3>
        {% if is_bound %}
            <p>Кнопка привязана</p>
            <form action="{% url "move_tasks_deadline_js:unbind_button" %}?type={{ handler_type }}" method="post">
                <button>Отвязать кнопку от окна с задачей</button>
            </form>
        {% else %}
            <p>Кнопка отвязана</p>
            <form action="{% url "move_tasks_deadline_js:bind_button" %}?type={{ handler_type }}" method="post">
                <button>Привязать кнопку к окну с задачей</button>
            </form>
        {% endif %}
    {% endfor %}
{% else %}
    <p>Привязать или отвязать кнопку может только администратор</p>
{% endif %}
</body>
</html>

move_tasks_deadline_js/templates/move_tasks_deadline_js/move_button.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title></title>
    <meta charset="UTF-8">
</head>
<body>
<h3>{{ button_type }}</h3>
{% if button_type == "js" %}
    <button
            id="move_tasks_deadline"
            title="Передвинуть крайний срок на день вперед"
            onclick="move_tasks_deadline()"
    >
        Не успеваю
    </button>
{% else %}
    <form method="post" action="{% url "move_tasks_deadline_js:move_deadline" %}?type={{ button_type }}">
    <button title="Передвинуть крайний срок на день вперед">
        Не успеваю
    </button>
    </form>
{% endif %}
</body>
{% if button_type == "js" %}
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>
{% endif %}
<script src="//api.bitrix24.com/api/v1/"></script>
<script src="{% static path_to_script %}"></script>
</html>